apiVersion: v1
kind: PersistentVolume
metadata:
  name: flink-pv
  labels:
    name: flink-pv
spec:
  capacity:
    storage: 3Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/flink-pvs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      name: flink-pv
