apiVersion: v1
kind: PersistentVolume
metadata:
  name: flink-pv
  labels:
    name: flink-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/flink-pvs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      name: flink-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc-claim-diagnosis-rawfiles
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      name: flink-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc-claim-procedure-rawfiles
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      name: flink-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc-claim-provider-rawfiles
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      name: flink-pv

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flink-pvc-healthcare-enriched
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      name: flink-pv
