apiVersion: v1
kind: Service
metadata:
  labels:
    app: flink-cluster-session-gateway
  name: flink-cluster-session-gateway-sqlgateway-rest
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: sqlgateway-rest
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: flink-cluster-session-gateway
    component: jobmanager
    type: flink-native-kubernetes
  sessionAffinity: None
  type: ClusterIP
