FROM deltaio/delta-docker:latest



# Add your configurations or setup if needed
# Set a custom log directory (optional)
RUN mkdir -p /tmp/spark-logs && chmod -R 777 /tmp/spark-logs

# Override the startup.sh to also start the Spark Thrift Server
RUN echo "/opt/spark/sbin/start-thriftserver.sh \
  --master local[*] \
  --conf spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension \
  --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog \
  --conf spark.sql.warehouse.dir=/opt/spark/delta-tables \
  --packages io.delta:delta-core_2.12:2.3.0" >> /opt/spark/sbin/startup.sh

USER root
ENTRYPOINT ["/opt/spark/sbin/startup.sh"]
